### ISSUE TITLE
J'ai l'impression que axSize ou axFrame ne me laisse pas resizer.

### ISSUE THREAD

**Issue by p-groarke** [alxarsenault/Orchestra#1]
Mes trucs ne peuvent pas resizer plus gros que mon axSize initial (500, 500)... Je Refresh() a l'interieur de mon mSize() et je fait rien de special. Mon code est pratiquement le meme que l'ancien projet.

Une idee? Tu peux voir mon code dans ma branche, dans la page github, click sur code, deux boutons en dessous tu voix le drop-down branch. La dedans choisi phil pour naviguer mes trucs si tu veux. Je pense pas que je fais quelque chose de weird...

**Comment by ghost** [comment]
c quoi le probleme ?

2013/3/4 Socapex notifications@github.com

**Comment by ghost** [comment]
comment je fait pour ouvrir ton code
