### ISSUE TITLE
[BAD] Master ne compile pas, besoin de irrlicht.dll...

### ISSUE THREAD

**Issue by p-groarke** [alxarsenault/Orchestra#7]
Est-ce que tu as inclus le dll dans le projet?

**Comment by ghost** [comment]
oui c p-e que j'ai changé les link options dans visual studio

**Comment by p-groarke** [comment]
Vous etes ou?

**Comment by p-groarke** [comment]
Ok, c'est quoi les options a changer? J'aimerais pouvoir compiler le main pour pouvoir voir l'ensemble. J'vais aussi p-e commencer le menu des lecons pcq Anis a pas d'lair tres actif sur git. Est-ce que le code est online?

**Comment by AnissK45** [comment]
non le code du panel je l ai sur mon ordi je vai te l envoy/ bientot.

**Comment by ghost** [comment]
Je comprend pu rien la. Le git a l'air pal mal foutu sur mon ordi, il y a plein de truc bizzard dans VideoInterface pi mediaPlaye. J'ai travailler toute la journee dessus pi sa marchais pourtant

**Comment by p-groarke** [comment]
guys. PULL AVANT DE COMMIT plz. Jvais rebooter en pc et essayer darranger ca mais jvais p-e reculer dans mon dernier merge. Headaches. Checker toujour sur le network tab avant de push vos truc pour voir si vous etes en retard.
